### ISSUE TITLE
Error when I start the app up | Discord: VMProjects [Iphone XR, 13.5]#3013

### ISSUE THREAD

**Issue by GXXCSGO** [lhaasper/3-Layer-protection-C-#1]
Unhandled Exception: System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Part1_Protect.Program.run_from_bytes(Byte[] bytes, String[] args)
   at Part1_Protect.Program.Main(String[] args)

**Comment by lhaasper** [comment]
Did you Include everything?
